### ISSUE TITLE
ERROR:    Invalid NZBLNK URI: missing 'h' parameter

### ISSUE THREAD

**Issue by Sabcoll** [Tensai75/nzb-monkey-go#10]
Hi,

I'm trying to push a file to my Synology. However I'm encountering the error

> ERROR:    Invalid NZBLNK URI: missing 'h' parameter

I'm not using categories, search engine is disabled.
Config is only changed in the SYNOLOGYDLS Section.
URL, Username and Password are correct / changed for upload.

![image](https://github.com/Tensai75/nzb-monkey-go/assets/14361005/a4f6282a-08ec-486b-877c-98fd28ac0b4a)

**Comment by Tensai75** [comment]
Github issues are for bug reports or enhancement requests.
For assistance in using the program, please ask on your favorite Usenet forum.

Hint: The NZBLNK you are providing to the program obviously does not contain a "h" parameter, so it does not even start searching (so your SynologyDLS settings are not the cause for this error).
