### ISSUE TITLE
On connection issue, app just crashes without displaying/logging anything on directsearch

### ISSUE THREAD

**Issue by reloxx13** [Tensai75/nzb-monkey-go#14]
When using high-way.me as directsearch reader, the app just crashes     
       
Only on port 563, port 443 worked     

> HWm Ports (SSL) | 563,443,465,993,4242

Steps to reproduce: disable other searchengines besides directsearch and just set an invalid port number of your provider eg 99999    

To resolve: Add catch and display an error message.

From logfile:

> 2023/09/27 15:11:16 INFO: NZB Monkey Go v0.1.6 started
> 2023/09/27 15:11:17 INFO: Arguments provided:
> 2023/09/27 15:11:17 INFO: NZBLNK:   nzblnk:///?t=XXXX&h=XXXXXX&p=XXXXXX&g=alt.binaries.ath&d=1695662198
> 2023/09/27 15:11:17 INFO: Title:    XXXXXX
> 2023/09/27 15:11:17 INFO: Header:   XXXXXX
> 2023/09/27 15:11:17 INFO: Password: XXXXXX
> 2023/09/27 15:11:17 INFO: Groups:   alt.binaries.ath
> 2023/09/27 15:11:17 INFO: Date:     25.09.2023 19:16:38
> 2023/09/27 15:11:17 INFO: Searching on NZB direct search ...
> 2023/09/27 15:11:17 INFO: Searching in group 'alt.binaries.ath' ...

```
# Settings for the nzb direct search
[DIRECTSEARCH]
# Your usenet server host name
host = "reader.high-way.me"
# Your usenet server port number
port = 563
# Use SSL
ssl = true
# Your usenet account username
username = "XXXXX"
# Your usenet account password
password = "XXXXX"
# Maximum allowed connections to your usenet server (default = 20)
connections = 20
# Number of hours to search backward from the provided date (default = 12)
hours = 24
# Number of hours to search forward from the provided date (default = 12)
forward_hours = 24
# Number of parallel scans (default = 50)
scans = 20
# Number of articles to load per scan (default = 20000)
step = 20000
# Skip direct search when using best_nzb and a good NZB file has already been found
skip = true
# Search only in the first group if several groups are provided
# (the chance to get different results in different groups is virtually 0)
first_group_only = false
```

**Comment by Tensai75** [comment]
Fixed with [v0.1.7](https://github.com/Tensai75/nzb-monkey-go/releases/tag/v0.1.7) (https://github.com/Tensai75/nzb-monkey-go/commit/933f82ef3d46716b0abcd92fc558711287fff5db)
