### ISSUE TITLE
NZB Monkey Go v0.17 Windows binary is detected as virus

### ISSUE THREAD

**Issue by redoXiD** [Tensai75/nzb-monkey-go#17]
It's probably a false positive but I just wanted to let you know that Chrome and also the Windows Defender detect the following file as a virus:

nzb-monkey-go_v0.1.7-windows-amd64.zip
Trojan:Script/Wacatac.H!ml

Somehow only the amd64 version is affected, for the 386 version Chrome just says that it is a suspicious file, no warnings from Windows Defender.

**Comment by Tensai75** [comment]
Windows Defender is well known to flag any previously unknown exe that establishes TCP connections as malware/trojans.
The executables were build automatically with the Github Action on a linux system. So there is virtually no possibility that they contain any malware/trojan.
If you have still doubts you always have the possibility to build the executable yourself.
