### ISSUE TITLE
No results found with new version, while old version gave an result

### ISSUE THREAD

**Issue by reloxx13** [Tensai75/nzb-monkey-go#20]
Heya,

in version 0.1.9 i get the following error:

>    NZB Monkey Go v0.1.9
> 
>    Arguments provided:
>    NZBLNK:   nzblnk:///?t=XXXXX.S01E01.GerSub.AAC.1080p.WEB.h264-XXXX&h=L1ExxyUzeRES73b5tan2OigyaNBCsVXOLnKtNVFdUCpmfnfIF7&p=YYY&g=alt.binaries.town&d=1696326282
>    Title:    XXXX.S01E01.GerSub.AAC.1080p.WEB.h264-Baka
>    Header:   L1ExxyUzeRES73b5tan2OigyaNBCsVXOLnKtNVFdUCpmfnfIF7
>    Password: YYY
>    Groups:   alt.binaries.town
>    Date:     03.10.2023 11:44:42 CEST
> 
>    Searching on NZBIndex ...
>    WARNING:  No results found
> 
>    Searching on Binsearch (most popular groups) ...
>    WARNING:  No results found
> 
>    Searching on Binsearch (other groups) ...
>    WARNING:  No results found
> 
>    Searching on NZBKing ...
>    WARNING:  No results found
> 
>    Searching on NZB direct search ...
> 
>    Searching in group 'alt.binaries.town' ...
>    Scanning from 30.09.2023 11:44:42 CEST to 06.10.2023 11:44:42 CEST
>    Scanning for first message number ... 100% |████████████████████████████████████████|  [5s]
>    Found first message number: 3816612443 / Date: 30.09.2023 11:45:12 CEST
>    Scanning for last message number ...  100% |████████████████████████████████████████|  [4s]
>    ERROR:    Error while scanning group 'alt.binaries.town' for the last message: start date of search range is newer than latest message of this group
> 
> 
>    ERROR:    No results found for header 'L1ExxyUzeRES73b5tan2OigyaNBCsVXOLnKtNVFdUCpmfnfIF7'

While it works with 0.1.4

>    NZB Monkey Go v0.1.4
> 
>    Arguments provided:
>    NZBLNK:   nzblnk:///?t=XXXX.S01E01.GerSub.AAC.1080p.WEB.h264-XXXX&h=L1ExxyUzeRES73b5tan2OigyaNBCsVXOLnKtNVFdUCpmfnfIF7&p=YYYY&g=alt.binaries.town&d=1696326282
>    Title:    XXX.S01E01.GerSub.AAC.1080p.WEB.h264-XXXX
>    Header:   L1ExxyUzeRES73b5tan2OigyaNBCsVXOLnKtNVFdUCpmfnfIF7
>    Password: YYY
>    Groups:   alt.binaries.town
>    Date:     03.10.2023 11:44:42
> 
>    Searching on NZBIndex ...
>    WARNING:  No results found
> 
>    Searching on Binsearch (most popular groups) ...
>    WARNING:  No results found
> 
>    Searching on Binsearch (other groups) ...
>    WARNING:  No results found
> 
>    Searching on NZBKing ...
>    WARNING:  No results found
> 
>    Searching on NZB direct search ...
> 
>    Searching in group 'alt.binaries.town' ...
>    Scanning from 30.09.2023 11:44:42 to 06.10.2023 11:44:42
>    Scanning for first message ID ... 100% |████████████████████████████████████████|
>    Scanning for last message ID ...  100% |████████████████████████████████████████|
>    Scanning messages ...             100% |████████████████████████████████████████|
>    Found:    [02/23] "L1ExxyUzeRES73b5tan2OigyaNBCsVXOLnKtNVFdUCpmfnfIF7.part01.rar" (1/147) (1.7 GB)
>    Files:    22/23 (Missing files: 1)
>    Segments: 2276/2276 (Missing segments: 0.000000 %)
>    Using NZB file from NZB direct search
> 
>    Automatic checking for categories ...
>    Using category 'series'
> 
>    Pushing the NZB file to SABnzbd...
>    SUCCESS:  The NZB file was pushed to SABnzbd

**Comment by Tensai75** [comment]
Fixed with [v0.1.10](https://github.com/Tensai75/nzb-monkey-go/releases/tag/v0.1.10) (https://github.com/Tensai75/nzb-monkey-go/commit/9996c5c9bda67dc48d0bd8a555eeaf69ed4ea438)
