### ISSUE TITLE
[FR] Password to NZB

### ISSUE THREAD

**Issue by theHornest** [Tensai75/nzb-monkey-go#30]
Hallo Tensai,
es würde mich freuen, wenn in zukünftigen Versionen von nzb-monkey-go
die Möglichkeit besteht das Passwort direkt in der NZB speichern zu lassen.

```
<head>
    <meta type="password">PASSWORT</meta>
  </head>
```

**Comment by Tensai75** [comment]
Das ist doch schon so...
Sofern im nzblnk oder in den Argumenten die Parameter p (Password) und t (Titel) angegeben sind, werden Passwort und Titel schon jetzt automatisch als Meta-Tags in die NZB-Datei reingeschrieben. Die NZB-Datei beginnt immer so:

```
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
  <!-- Downloaded from SOURCE with NZB Monkey Go  -->
  <head>
    <meta type="title">TITEL</meta>
    <meta type="password">PASSWORD</meta>
  </head>```
